project_name: zerotrust
builds:
  - main: ./zerotrust.go
    binary: zt
    flags:
      - -trimpath
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
archives:
  - id: darwin
    replacements:
      darwin: Darwin
      amd64: x86_64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
before:
  hooks:
    - go mod download
brews: 
  - 
   tap:
    owner: adedayo
    name: homebrew-tap
   commit_author:
    name: "Dayo Adetoye"
    email: dayo.dev@gmail.com
   caveats: "To get help running ZeroTrust please run: zt --help "
   homepage: "https://github.com/adedayo/zerotrust"
   description: "zerotrust is a zero trust architecture modelling and analysis tool."
   license: "BSD-3-Clause"
